Update elip.py
Just learned about lib2geom, don't quite know what it's about :) So I realized that there are some python files like elip.py, that didn't require anything to be built per se. However, elip.py tended to break on my Ubuntu 18.04 with

```
$ python elip.py 
Traceback (most recent call last):
  File "elip.py", line 111, in display
    draw_elip(da.window, handles)
  File "elip.py", line 77, in draw_elip
    w.draw_line(g, ox, oy, six.x, six.y)
TypeError: integer argument expected, got float
Traceback (most recent call last):
  File "elip.py", line 111, in display
    draw_elip(da.window, handles)
  File "elip.py", line 77, in draw_elip
    w.draw_line(g, ox, oy, six.x, six.y)
TypeError: integer argument expected, got float
^CTraceback (most recent call last):
  File "elip.py", line 153, in <module>
    gtk.main()
KeyboardInterrupt
```

So I've just added the required int castings to this file, and now I can run this file, and it draws.