Update test_py2geom.py
I have tried to build `lib2geom` on Ubuntu 18.04, it builds fine ( my build notes are at https://sourceforge.net/p/sdaaubckp/code/HEAD/tree/source-build-scripts/get-lib2geom.sh ).

Then I tried to use `test_py2geom.py` to test the Python bindings, and had a ton of errors. Since this is the first time I see `lib2geom`, and I don't really know how it works, I simply tried to guess what changes had been made by reading the source code.

With the proposed file change in this PR, now this script runs fully without exceptions on Ubuntu 18.04 - though I have no idea if it is (mathematically) correct; the printout I get from this edit is:

```
$ python test_py2geom.py 
(1.0, 2.0) (31.0, 2.0)
L1: 3.0
L2: 2.2360679775
L2sq: 5.0
LInfty: 2.0
is_zero: False
atan2: 1.10714871779
rot90: (-2.0, 1.0)
unit_vector: (0.4472135955, 0.894427191)
abs: (1.0, 2.0)
dot: 35.0
angle_between: -1.04272187837
distance: 30.0
distanceSq: 900.0
cross: -60.0
is_unit_vector: False
a == b False
Lerp: (10.0, 2.0)
Bezier(2, 3)
2.3
{3, 2}s^0
<py2geom._py2geom.PiecewiseSBasis object at 0x7f3df24fb8a0>
{0, 0.125}s^0
[<py2geom._py2geom.SBasis object at 0x7f3df249d150>]
0
[]
{0, 0}s^0
[]
[1.5]
```
So, if my guesses have been incorrect, obviously no need to merge this PR - though it would be nice if this script is updated, so it runs on an Ubuntu 18.04 build.

In case it might be useful to someone else, here are also my notes that I took (inline as comments in the script) during the process of finding the commands in this update:

```
#!/usr/bin/python

import py2geom as g

a = g.Point(1,2)
b = g.Point(31,2)
print a, b

"""
$ python test_py2geom.py
(1.0, 2.0) (31.0, 2.0)
L1: 3.0
L2: 2.2360679775
L2sq: 5.0
LInfty: 2.0
is_zero: False
is_unit_vector:
Traceback (most recent call last):
  File "test_py2geom.py", line 15, in <module>
    print "%s:" % i, g.__dict__[i](a)
Boost.Python.ArgumentError: Python argument types in
    py2geom._py2geom.is_unit_vector(Point)
did not match C++ signature:
    is_unit_vector(Geom::Point, double)

# after that fix:
Traceback (most recent call last):
  File "test_py2geom.py", line 24, in <module>
    bo = g.BezOrd(2,3)
AttributeError: 'module' object has no attribute 'BezOrd'
"""

point_fns_1 = ["L1", "L2", "L2sq", "LInfty", "is_zero",
             "atan2", "rot90",
             "unit_vector", "abs"]
point_fns_2 = ["dot", "angle_between", "distance", "distanceSq", "cross"]
point_fns_3 = [ "is_unit_vector", ]

for i in point_fns_1:
    print "%s:" % i, g.__dict__[i](a)
for i in point_fns_2:
    print "%s:" % i, g.__dict__[i](a,b)
for i in point_fns_3:
    print "%s:" % i, g.__dict__[i](a,0)
print "a == b", a == b
print "Lerp:", g.lerp(0.3, a,b)

# bo = g.BezOrd(2,3)
# print bo
# print bo.point_at(0.3)
#
# AttributeError: 'module' object has no attribute 'BezOrd'
#
#./doc/tutorial.txt:(12:27:41) ACSpike: what are BezOrds?
#./doc/tutorial.txt:(12:30:14) njh: Bezier Ordinal
#./doc/tutorial.txt:(12:30:27) njh: you can think of them as linear bezier segments
#
# no more BezOrd in lib2geom, nor inkscape:
# https://gitlab.com/search?utf8=%E2%9C%93&snippets=&scope=&search=BezOrd&project_id=3472737
# have ./src/2geom/bezier-utils.cpp:bezier_pt(unsigned const degree, Point const V[], double const t)
# also:
#./src/toys/match-curve.cpp:38:    PointSetHandle psh;
#./src/toys/match-curve.cpp-142-        for(int i = 0; i < 6; i++)
#./src/toys/match-curve.cpp:143:            psh.push_back(uniform()*400, uniform()*400);
#./src/toys/match-curve.cpp:54:        D2<SBasis> B = psh.asBezier();
#./src/toys/match-curve.cpp:76:        double lo = 0, hi = 1;
#./src/toys/match-curve.cpp:79:            double mid = (hi + lo)/2;
#./src/toys/match-curve.cpp:82:            m = truncate(compose(B, Linear(0, mid)), 2);
#./src/toys/match-curve.cpp:121:                hi = mid;
#./src/toys/match-curve.cpp:127:        //draw_cross(cr, point_at(B, hi));
#./src/toys/match-curve.cpp:128:        draw_circ(cr, m(hi));

#  point_at(B, hi) -> m(hi): truncate(compose(psh.asBezier(), Linear( 0, ((hi + lo)/2) )), 2)(psh.asBezier(), hi)

#./src/toys/toyframework.py:49:class PointSetHandle(Handle):
#./src/cython/test-primitives.py:142:        k = Line.from_points(Point(), Point(2, 1))
#./src/cython/test-primitives.py:147:            k.point_at(43),
#./src/cython/test-curves.py:174:        D = Bezier(2, 4)
#./src/cython/test-curves.py:313:        K = LineSegment.from_beziers(Bezier(2, 8), Bezier(-1, 9))
#./src/cython/test-curves.py:340:        C = CubicBezier(Point(2, 0), Point(-1, 2.9), Point(-2, 3), Point(3, 1))
#./src/cython/test-curves.py:341:        D = CubicBezier.from_beziers(Bezier(2, 8, 4, 7), Bezier(-1, 9, 9, 8))

#./src/cython/_cy_curves.pyx=13=cdef class cy_Curve:
#./src/cython/_cy_curves.pyx:47:    def point_at(self, Coord t):
#./src/cython/_cy_curves.pyx=1039=cdef class cy_BezierCurve :
#./src/cython/_cy_curves.pyx:1179:    def point_at(self, Coord t):
#./src/cython/test-curves.py:303:        C = BezierCurve.create( [ Point(0,1), Point(1, 0) ] )

# there is only Bezier, no BezierCurve in ./src/py2geom/bezier.cpp
# point_at is only present in src/cython, for classes cy_Curve, cy_SBasisCurve, cy_BezierCurve, cy_HLineSegment, cy_VLineSegment, cy_EllipticalArc, cy_Path, cy_Line, cy_Ray

#bo = g.BezOrd(2,3) #AttributeError: 'module' object has no attribute 'BezOrd'
#bo = g.Bezier(2,3) #AttributeError: 'Bezier' object has no attribute 'point_at'
#bo = g.BezierCurve(2,3) #AttributeError: 'module' object has no attribute 'BezierCurve'
bo = g.Bezier(2,3)
print bo
print bo.valueAt(0.3)

# in py2geom, only d2, sbasis, linear, ray, line, path (PathVector) have reverse()
# in cython, cy_Curve, cy_SBasis, cy_SBasisCurve, cy_BezierCurve, cy_LineSegment, cy_QuadraticBezier, cy_CubicBezier, cy_HLineSegment, cy_VLineSegment, cy_EllipticalArc, cy_Path, cy_Line, cy_Ray have reverse
# from ./src/py2geom/path.cpp, seems class_<Geom::Path>("Path") is replacement for LineSegment, QuadraticBezier, CubicBezier
print g.reverse(bo.toSBasis())

# g.SBasis(0.0) seems to match C++ signature __init__(_object*, double)
# g.SBasis(0.0, 0.0) seems to match C++ signature __init__(_object*, double, double)
#

  import py2geom as g
  gpb=g.PiecewiseSBasis(g.Bezier(0.0,8.0).toSBasis())
  #g.sin(gpb, 0.0, 1) # segfault
  g.sin(gpb, 0.1, 1) # OK, seems to match C++ signature sin(Geom::Piecewise<Geom::SBasis>, double, int)
  g.sin(gpb, 1, 1) # OK
  g.path_from_sbasis( g.D2SBasis(sb, sb), 0.0, True ) # segfaults
  g.path_from_sbasis( g.D2SBasis(sb, sb), 1.0, True ) # ok
  g.path_from_sbasis( g.D2SBasis(sb, sb), 0.01, False ) # ok

#sn = g.sin(g.BezOrd(0.0,8.0),5)
sn = g.sin(g.PiecewiseSBasis(g.Bezier(0.0,8.0).toSBasis()), 5, 0)
print sn
#print g.inverse(sn,10) # did not match C++ signature: inverse(Geom::SBasis, int)
print g.inverse(g.Bezier(0.0,8.0).toSBasis(),10)
print list(sn)

r_sn = g.roots(sn)
print len(r_sn)
print list(r_sn)

#bo = g.BezOrd(-1,1)
bo = g.Bezier(-1,1)
#sb = g.SBasis() # did not match C++ signature: __init__(_object*, double); __init__(_object*, double, double); __init__(_object*, Geom::Linear)
sb = g.SBasis(0)
print sb
print list(g.roots(sb))
sb.append(bo)
print list(g.roots(sb))

"""
g.SBasis; C++ signature:
          __init__(_object*, double)
          __init__(_object*, double, double)
          __init__(_object*, Geom::Linear)

g.D2SBasis; C++ signature:
            __init__(_object*, Geom::SBasis, Geom::SBasis)
            __init__(_object*)

g.reverse;  C++ signature:
            reverse(Geom::D2<Geom::SBasis>)
            reverse(Geom::Linear)
            reverse(Geom::Linear)
            reverse(Geom::SBasis)

g.sin;  C++ signature:
        sin(Geom::Piecewise<Geom::SBasis>, double, int)

g.inverse;  C++ signature:
            inverse(Geom::SBasis, int)

g.path_from_sbasis; C++ signature:
                    path_from_sbasis(Geom::D2<Geom::SBasis>, double, bool)

g.Path().appendPortionTo; C++ signature:
                          appendPortionTo(Geom::Path {lvalue}, Geom::Path {lvalue}, double, double)

g.roots;  C++ signature:
          roots(Geom::Piecewise<Geom::SBasis>)
          roots(Geom::SBasis)

>>> g.D2SBasis(sb, bo.toSBasis()).pointAt(0)
(0.0, -1.0)
>>> g.D2SBasis(sb, bo.toSBasis()).pointAt(1)
(0.0, 1.0)

>>> g.D2SBasis(bo.toSBasis(), sb).pointAt(0)
(-1.0, 0.0)
>>> g.D2SBasis(bo.toSBasis(), sb).pointAt(1)
(1.0, 0.0)

>>> g.D2SBasis(bo.toSBasis(), bo.toSBasis()).pointAt(0)
(-1.0, -1.0)
>>> g.D2SBasis(bo.toSBasis(), bo.toSBasis()).pointAt(1)
(1.0, 1.0)

>>> g.path_from_sbasis( g.D2SBasis(g.SBasis(0), g.SBasis(1)), 0.01, True ).pointAt(0)
(0.0, 1.0)
>>> g.path_from_sbasis( g.D2SBasis(g.SBasis(0), g.SBasis(1)), 0.01, True ).pointAt(1)
(0.0, 1.0)

>>> g.path_from_sbasis( g.D2SBasis(g.SBasis(1), g.SBasis(1)), 0.01, True ).pointAt(0)
(1.0, 1.0)
>>> g.path_from_sbasis( g.D2SBasis(g.SBasis(1), g.SBasis(1)), 0.01, True ).pointAt(1)
(1.0, 1.0)

>>> print(g.path_from_sbasis( g.D2SBasis(sb, bo.toSBasis()), 0.01, False ).appendPortionTo( g.path_from_sbasis(g.D2SBasis(), 0.01, False), 0.1, 0.2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: lib2geom exception: Non-contiguous path lib2geom_git/src/2geom/path.cpp:919)

>>> g.path_from_sbasis( g.D2SBasis(sb, bo.toSBasis()), 0.01, False ).pointAt(0)
(0.0, -1.0)
>>> g.path_from_sbasis( g.D2SBasis(sb, bo.toSBasis()), 0.01, False ).pointAt(1)
(0.0, 1.0)

>>> g.SBasis(0,-1).valueAt(0)
0.0
>>> g.SBasis(0,-1).valueAt(1)
-1.0


>>> g.path_from_sbasis( g.D2SBasis(sb, g.SBasis(-1)), 0.01, False ).pointAt(0)
(0.0, -1.0)
>>> g.path_from_sbasis( g.D2SBasis(sb, g.SBasis(-1)), 0.01, False ).pointAt(1)
(0.0, -1.0)
>>> g.path_from_sbasis(g.D2SBasis(sb, bo.toSBasis()), 0.01, False).pointAt(0)
(0.0, -1.0)
>>> g.path_from_sbasis(g.D2SBasis(sb, bo.toSBasis()), 0.01, False).pointAt(1)
(0.0, 1.0)
>>> g.path_from_sbasis( g.D2SBasis(sb, g.SBasis(-1)), 0.01, False ).appendPortionTo( g.path_from_sbasis(g.D2SBasis(sb, bo.toSBasis()), 0.01, False), 1, 1) # passes


>>> p2 = g.path_from_sbasis( g.D2SBasis(g.Bezier(0,1).toSBasis(), g.Bezier(0,-1).toSBasis()), 0.01, False )
>>> p1.initialPoint(); p1.finalPoint(); p2.initialPoint(); p2.finalPoint();
(0.0, 0.0)
(0.0, -1.0)
(0.0, 0.0)
(1.0, -1.0)

>>> p1.appendPortionTo(p2, 0, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: lib2geom exception: Non-contiguous path (/media/data1/src/lib2geom_git/src/2geom/path.cpp:919)
>>> p1.appendPortionTo(p2, 1, 1)
>>>

>>> len(g.roots( g.SBasis(-1) ))
0
>>> len(g.roots( g.SBasis(1) ))
0
>>> len(g.roots( g.SBasis(0,1) ))
1

>>> g.roots( g.SBasis(0,1) )[0]
-0.0
>>> g.roots( g.SBasis(1,0) )[0]
1.0
>>> g.roots( g.SBasis(0.5,0) )[0]
1.0

>>> g.SBasis(0.5,0)[0]
<0.5, 0.0>

>>> str( g.SBasis(0.5,0) )
'{0.5, 0}s^0'

>>> g.SBasis(0.5,0).at0()
0.5
>>> g.SBasis(0.5,0).at1()
0.0

>>> g.SBasis(1,1).isZero(0)
False
>>> g.SBasis(1,1).isZero(1)
True
>>> g.SBasis(0,1).isZero(0)
False
>>> g.SBasis(0,1).isZero(1)
True
>>> g.SBasis(1,0).isZero(0)
False
>>> g.SBasis(1,0).isZero(1)
True

>>> g.path_from_sbasis( g.D2SBasis(g.SBasis(0,1), g.SBasis(1,0)), 0.01, False).pointAt(0)
(0.0, 1.0)
>>> g.path_from_sbasis( g.D2SBasis(g.SBasis(0,1), g.SBasis(1,0)), 0.01, False).pointAt(1)
(1.0, 0.0)
>>> ps=g.path_from_sbasis( g.D2SBasis(g.SBasis(0,1), g.SBasis(1,0)), 2, True); ps.pointAt(0); ps.pointAt(1)
(0.0, 1.0)
(1.0, 0.0)

>>> ps1=g.path_from_sbasis( g.D2SBasis(g.SBasis(0,1), g.SBasis(1,0)), 1, True); ps2=g.path_from_sbasis( g.D2SBasis(g.SBasis(1,2), g.SBasis(0,-1)), 1, True);
>>> ps1.initialPoint(); ps1.finalPoint(); ps2.initialPoint(); ps2.finalPoint();
(0.0, 1.0)
(1.0, 0.0)
(1.0, 0.0)
(2.0, -1.0)
>>> ps1.appendPortionTo(ps2, 0, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: lib2geom exception: Non-contiguous path (/media/data1/src/lib2geom_git/src/2geom/path.cpp:919)
>>> ps2.appendPortionTo(ps1, 0, 1)
>>> ps1.initialPoint(); ps1.finalPoint(); ps2.initialPoint(); ps2.finalPoint();
(0.0, 1.0)
(2.0, -1.0)
(1.0, 0.0)
(2.0, -1.0)

d21=g.D2SBasis(g.SBasis(0,1), g.SBasis(1,0)); d22=g.D2SBasis(g.SBasis(1,2), g.SBasis(0,-1)); ps1=g.path_from_sbasis( d21, 1, True); ps2=g.path_from_sbasis( d22, 1, True);

>>> pws = g.PiecewiseSBasis(g.SBasis(0,1))
>>> pws
<py2geom._py2geom.PiecewiseSBasis object at 0x7f3f80f7dd60>
>>> pwsB = g.compose(pws, g.SBasis(1,2))
>>> pwsB
<py2geom._py2geom.PiecewiseSBasis object at 0x7ff1471f58a0>

>>> pwsB[0]
<py2geom._py2geom.SBasis object at 0x7ff147197150>
>>> pwsB[1]
Traceback (most recent call last):

>>> pwsB.concat(pws)
>>> pwsB[1]
<py2geom._py2geom.SBasis object at 0x7ff147197150>
"""
```